name: shelf3d_106_stable_velocity

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    base_image:
      shape: [3, 84, 84]
      type: rgb
    wrist_image:
      shape: [3, 84, 84]
      type: rgb
    overview_image:
      shape: [3, 84, 84]
      type: rgb
    robot_state:
      shape: [11]
      # type default: low_dim
    env_state:
      shape: [23]
  action: 
    shape: [11]

dataset_path: &dataset_path data/${task.name}.hdf5
abs_action: &abs_action False

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  delta_action: False
  seed: 42
  val_ratio: 0.0
