name: 01_20_test_1

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    base_image:
      shape: [3, 224, 224]
      type: rgb
    wrist_image:
      shape: [3, 224, 224]
      type: rgb
    overview_image:
      shape: [3, 224, 224]
      type: rgb
    base_pose:
      shape: [3]
      # type default: low_dim
    arm_pos:
      shape: [3]
    arm_quat:
      shape: [4]
    gripper_pos:
      shape: [1]
  action: 
    shape: [13]

dataset_path: &dataset_path data/${task.name}.hdf5
abs_action: &abs_action True

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  seed: 42
  val_ratio: 0.0
